# Generated by Django 5.1.7 on 2025-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fix_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_1c',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
