# Generated by Django 5.2.3 on 2025-06-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code_1c',
            new_name='external_id',
        ),
    ]
