# Generated by Django 5.1.7 on 2025-07-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('детские', 'детские'), ('подростковые', 'подростковые')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Luceat', 'Luceat'), ('Cormens', 'Cormens'), ('MonSolis', 'MonSolis'), ('Piccolo Pesce', 'Piccolo Pesce')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bridge_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('черный', 'черный'), ('серебро', 'серебро'), ('золото', 'золото'), ('цветные', 'цветные')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('мужские', 'мужские'), ('женские', 'женские'), ('унисекс', 'унисекс')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('металл', 'металл'), ('пластик', 'пластик'), ('комбинированные', 'комбинированные'), ('титан', 'титан')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='temple_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
